import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :overstats, OverstatsWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :overstats, FreethymeWeb.Endpoint,
  url: [host: "overstats.gigalixirapp.com", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  check_origin: ["//overstats.gigalixirapp.com"]

# Configures Swoosh API Client
config :swoosh, :api_client, Overstats.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :overstats, Freethyme.Repo, ssl: true
